import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import PageTitle from "../../components/ui/PageTitle";
import Card from "../../components/ui/Card";
import Button from "../../components/ui/Button";
import { api } from "../../lib/api";

const API_BASE = import.meta.env.VITE_API_BASE || "";

export default function PdfReportPage() {
  const [searchParams] = useSearchParams();
  const hasAutoGenerated = useRef(false);
  const [orgName, setOrgName] = useState("Aegis Global Logistics");
  const [target, setTarget] = useState("https://example.com");
  const [author, setAuthor] = useState("Senior Analyst");
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [generating, setGenerating] = useState(false);

  async function generate(includePdf = false) {
    setError("");
    setGenerating(true);
    try {
      const data = await api.report({ org_name: orgName, target, author, include_pdf: includePdf });
      setResult(data);
    } catch (e) {
      setError(String(e.message || e));
    } finally {
      setGenerating(false);
    }
  }

  useEffect(() => {
    const targetFromQuery = searchParams.get("target");
    const autogen = searchParams.get("autogen") === "1";

    if (targetFromQuery) {
      setTarget(targetFromQuery);
    }

    if (autogen && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      const run = async () => {
        setError("");
        setGenerating(true);
        try {
          const data = await api.report({
            org_name: orgName,
            target: targetFromQuery || target,
            author,
            include_pdf: false,
          });
          setResult(data);
        } catch (e) {
          setError(String(e.message || e));
        } finally {
          setGenerating(false);
        }
      };
      run();
    }
  }, [searchParams]);

  function viewFull() {
    window.print();
  }

  async function downloadPDF() {
    if (!result?.pdf_path) {
      // Generate the report with PDF first
      setError("");
      setGenerating(true);
      try {
        const data = await api.report({
          org_name: orgName,
          target,
          author,
          include_pdf: true,
        });
        setResult(data);
        // Trigger download after report is generated
        if (data.pdf_path) {
          const filename = data.pdf_path.split(/[\\/]/).pop();
          await downloadPdfFile(filename);
        }
      } catch (e) {
        setError(String(e.message || e));
      } finally {
        setGenerating(false);
      }
    } else {
      // PDF already generated, just download it
      const filename = result.pdf_path.split(/[\\/]/).pop();
      await downloadPdfFile(filename);
    }
  }

  async function downloadPdfFile(filename) {
    try {
      const token = localStorage.getItem("auth_token");
      const fullUrl = `${API_BASE}/api/report/download?filename=${encodeURIComponent(filename)}`;
      
      const headers = {};
      if (token) {
        headers.Authorization = `Bearer ${token}`;
      }

      // Fetch the PDF as a blob
      const response = await fetch(fullUrl, { headers });
      if (!response.ok) {
        throw new Error(`Download failed: ${response.statusText}`);
      }

      const blob = await response.blob();
      
      // Create blob URL and download
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = filename;
      
      // Append to body, click, and remove (necessary for mobile)
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Cleanup blob URL
      window.URL.revokeObjectURL(blobUrl);
    } catch (e) {
      setError(`Download failed: ${e.message}`);
    }
  }

  function emailReport() {
    const subject = encodeURIComponent(`Security Report: ${orgName}`);
    const body = encodeURIComponent(
      `Organisation: ${orgName}\nTarget: ${target}\nAuthor: ${author}\n\n${result?.pdf_path ? `Generated PDF: ${result.pdf_path}` : "Generate the report first to include PDF path."}`,
    );
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  function getSeverityColor(level) {
    switch (level?.toLowerCase()) {
      case "critical":
        return { bg: "#ff2d55", text: "#fff", label: "🔴 CRITICAL - Immediate action required" };
      case "high":
        return { bg: "#ff9500", text: "#fff", label: "🟠 HIGH - Needs urgent attention" };
      case "medium":
        return { bg: "#ffcc00", text: "#000", label: "🟡 MEDIUM - Should be addressed soon" };
      case "low":
        return { bg: "#34c759", text: "#fff", label: "🟢 LOW - Minor issue" };
      default:
        return { bg: "#a0a0a0", text: "#fff", label: "ℹ️ INFO" };
    }
  }

  function getSecurityGrade(score) {
    if (score >= 80) return { grade: "A", label: "Excellent", color: "#34c759" };
    if (score >= 60) return { grade: "B", label: "Good", color: "#ffcc00" };
    if (score >= 40) return { grade: "C", label: "Fair", color: "#ff9500" };
    return { grade: "D", label: "Poor", color: "#ff2d55" };
  }

  const reportContent = result ? (
    <div style={{ maxHeight: "70vh", overflowY: "auto" }}>
      {/* Header */}
      <div style={{ marginBottom: 40 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}>
          <div style={{ width: 40, height: 40, background: "#3B82F6", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800 }}>🔐</div>
          <div>
            <div style={{ fontSize: 28, fontWeight: 800, color: "var(--text)" }}>Security Report</div>
            <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>{orgName}</div>
          </div>
        </div>
      </div>

      {/* Overall Security Score */}
      <div style={{ background: "var(--surface-high)", border: "1px solid var(--ghost)", borderRadius: 12, padding: 24, marginBottom: 24 }}>
        <div style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 12, fontWeight: 800, textTransform: "uppercase" }}>Your Security Score</div>
        <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
          <div>
            <div style={{ fontSize: 48, fontWeight: 800, color: getSecurityGrade(result.summary.security_score || 0).color }}>
              {result.summary.security_score || 0}
            </div>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", marginTop: 4 }}>out of 100</div>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 18, fontWeight: 800, color: getSecurityGrade(result.summary.security_score || 0).color, marginBottom: 8 }}>
              Grade: {getSecurityGrade(result.summary.security_score || 0).grade}
            </div>
            <div style={{ fontSize: 13, color: "var(--text)", lineHeight: 1.6 }}>
              {getSecurityGrade(result.summary.security_score || 0).grade === "A" && "Excellent security posture. Keep up with updates and monitoring."}
              {getSecurityGrade(result.summary.security_score || 0).grade === "B" && "Good security practices. Address the identified medium-priority issues."}
              {getSecurityGrade(result.summary.security_score || 0).grade === "C" && "Fair security level. Multiple issues need attention to reduce risk."}
              {getSecurityGrade(result.summary.security_score || 0).grade === "D" && "Poor security posture. Critical and high-risk issues must be addressed immediately."}
            </div>
          </div>
        </div>
      </div>

      {/* Threats Summary */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 16, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>🎯 Threat Overview</div>
        <div className="grid grid-2" style={{ gap: 12, marginBottom: 12 }}>
          <div style={{ background: "var(--surface)", border: "1px solid var(--ghost)", borderRadius: 8, padding: 16 }}>
            <div style={{ fontSize: 11, color: "var(--text-secondary)", marginBottom: 6, fontWeight: 800 }}>Security Events Detected</div>
            <div style={{ fontSize: 32, fontWeight: 800, color: "#3B82F6" }}>{result.summary.siem?.events || 0}</div>
            <div style={{ fontSize: 11, color: "var(--text-secondary)", marginTop: 8 }}>Total suspicious activities across your systems</div>
          </div>
          <div style={{ background: "var(--surface)", border: "1px solid var(--ghost)", borderRadius: 8, padding: 16 }}>
            <div style={{ fontSize: 11, color: "var(--text-secondary)", marginBottom: 6, fontWeight: 800 }}>Malware Checks</div>
            <div style={{ fontSize: 28, fontWeight: 800, color: result.summary.virustotal?.malicious > 0 ? "#ff2d55" : "#34c759" }}>
              {result.summary.virustotal?.malicious || 0}
            </div>
            <div style={{ fontSize: 11, color: "var(--text-secondary)", marginTop: 8 }}>Scanned with {result.summary.virustotal?.total_engines || 0} security engines</div>
          </div>
        </div>
      </div>

      {/* Critical Vulnerabilities Section */}
      {result.details?.vulnerabilities && result.details.vulnerabilities.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 16, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>🔍 Detailed Security Issues Found</div>
          <div style={{ display: "grid", gap: 10 }}>
            {result.details.vulnerabilities.slice(0, 10).map((vuln, idx) => {
              const sevColor = getSeverityColor(vuln.severity);
              return (
                <div key={idx} style={{ background: "var(--surface)", border: `2px solid ${sevColor.bg}40`, borderRadius: 8, padding: 12 }}>
                  <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
                    <div style={{ width: 40, height: 40, background: sevColor.bg, borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 18, flexShrink: 0 }}>
                      {vuln.severity === "CRITICAL" && "🔴"}
                      {vuln.severity === "HIGH" && "🟠"}
                      {vuln.severity === "MEDIUM" && "🟡"}
                      {vuln.severity === "LOW" && "🟢"}
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 13, fontWeight: 800, color: "var(--text)", marginBottom: 4 }}>{vuln.name}</div>
                      <div style={{ fontSize: 11, color: "var(--text-secondary)", marginBottom: 8, lineHeight: 1.4 }}>
                        {vuln.evidence || "Security check identified this issue"}
                      </div>
                      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", fontSize: 10 }}>
                        <div style={{ background: "rgba(255,255,255,0.1)", padding: "4px 8px", borderRadius: 4, color: sevColor.bg }}>
                          <strong>Severity:</strong> {vuln.severity}
                        </div>
                        {vuln.cvss && (
                          <div style={{ background: "rgba(255,255,255,0.1)", padding: "4px 8px", borderRadius: 4 }}>
                            <strong>Risk Score:</strong> {vuln.cvss}/10
                          </div>
                        )}
                        {vuln.cve_id && vuln.cve_id !== "N/A" && (
                          <div style={{ background: "rgba(255,255,255,0.1)", padding: "4px 8px", borderRadius: 4 }}>
                            <strong>Reference:</strong> {vuln.cve_id}
                          </div>
                        )}
                        <div style={{ background: "rgba(255,255,255,0.1)", padding: "4px 8px", borderRadius: 4 }}>
                          <strong>Source:</strong> {vuln.source === "nuclei" ? "Security Scanner" : vuln.source === "wpscan" ? "CMS Plugin Check" : "System Check"}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
            {result.details.vulnerabilities.length > 10 && (
              <div style={{ background: "rgba(255,255,255,0.05)", borderRadius: 8, padding: 12, textAlign: "center", color: "var(--text-secondary)" }}>
                ... and {result.details.vulnerabilities.length - 10} more issues
              </div>
            )}
          </div>
        </div>
      )}

      {/* Vulnerabilities Summary */}
      {result.summary.vulnerability_summary && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 14, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>⚠️ Issues by Severity</div>
          <div style={{ display: "grid", gap: 10 }}>
            {result.summary.vulnerability_summary?.critical > 0 && (
              <div style={{ background: "#ff2d55", borderRadius: 8, padding: 14, color: "#fff" }}>
                <div style={{ fontWeight: 800, fontSize: 14, marginBottom: 4 }}>🔴 {result.summary.vulnerability_summary.critical} Critical Issues</div>
                <div style={{ fontSize: 12, opacity: 0.9 }}>These are serious security flaws that need to be fixed immediately. They could allow attackers to access your system.</div>
              </div>
            )}
            {result.summary.vulnerability_summary?.high > 0 && (
              <div style={{ background: "#ff9500", borderRadius: 8, padding: 14, color: "#fff" }}>
                <div style={{ fontWeight: 800, fontSize: 14, marginBottom: 4 }}>🟠 {result.summary.vulnerability_summary.high} High-Risk Issues</div>
                <div style={{ fontSize: 12, opacity: 0.9 }}>Important problems that could make your system vulnerable. Should be addressed within days.</div>
              </div>
            )}
            {result.summary.vulnerability_summary?.medium > 0 && (
              <div style={{ background: "#ffcc00", borderRadius: 8, padding: 14, color: "#000" }}>
                <div style={{ fontWeight: 800, fontSize: 14, marginBottom: 4 }}>🟡 {result.summary.vulnerability_summary.medium} Medium Issues</div>
                <div style={{ fontSize: 12, opacity: 0.9 }}>Worth fixing but not immediately urgent. Plan to address these in your next maintenance cycle.</div>
              </div>
            )}
            {result.summary.vulnerability_summary?.low > 0 && (
              <div style={{ background: "#34c759", borderRadius: 8, padding: 14, color: "#fff" }}>
                <div style={{ fontWeight: 800, fontSize: 14, marginBottom: 4 }}>🟢 {result.summary.vulnerability_summary.low} Minor Issues</div>
                <div style={{ fontSize: 12, opacity: 0.9 }}>Small issues with low risk. Can be fixed during regular maintenance.</div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Defence Checks */}
      {result.summary.defence && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 16, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>✓ Security Configuration Checks</div>
          <div style={{ display: "grid", gap: 8 }}>
            <div style={{ background: "var(--surface)", border: "1px solid var(--ghost)", borderRadius: 8, padding: 12, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontSize: 13, color: "var(--text)" }}>✅ Passed Security Tests</span>
              <span style={{ fontSize: 18, fontWeight: 800, color: "#34c759" }}>{result.summary.defence.pass || 0}</span>
            </div>
            <div style={{ background: "var(--surface)", border: "1px solid var(--ghost)", borderRadius: 8, padding: 12, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontSize: 13, color: "var(--text)" }}>❌ Failed Tests (Needs Fix)</span>
              <span style={{ fontSize: 18, fontWeight: 800, color: "#ff2d55" }}>{result.summary.defence.fail || 0}</span>
            </div>
            <div style={{ background: "var(--surface)", border: "1px solid var(--ghost)", borderRadius: 8, padding: 12, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <span style={{ fontSize: 13, color: "var(--text)" }}>⚠️ Warnings (Review Needed)</span>
              <span style={{ fontSize: 18, fontWeight: 800, color: "#ff9500" }}>{result.summary.defence.warn || 0}</span>
            </div>
          </div>

          {result.details?.defence_checks && result.details.defence_checks.length > 0 && (
            <div style={{ marginTop: 12, display: "grid", gap: 8 }}>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", fontWeight: 800 }}>DETAILED CHECKS</div>
              {result.details.defence_checks.map((check, idx) => (
                <div key={idx} style={{ background: "var(--surface)", borderRadius: 6, padding: 10, borderLeft: `3px solid ${check.status === "PASS" ? "#34c759" : check.status === "FAIL" ? "#ff2d55" : "#ff9500"}` }}>
                  <div style={{ fontSize: 12, color: "var(--text)", fontWeight: 600, marginBottom: 4 }}>
                    {check.status === "PASS" && "✓"} {check.status === "FAIL" && "✗"} {check.status === "WARN" && "⚠"} {check.name || check.check}
                  </div>
                  <div style={{ fontSize: 10, color: "var(--text-secondary)" }}>{check.description || check.detail || "Security configuration item"}</div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* SIEM Events */}
      {result.details?.siem_events && result.details.siem_events.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 16, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>📊 Detected Security Events</div>
          <div style={{ display: "grid", gap: 8 }}>
            {result.details.siem_events.slice(0, 8).map((event, idx) => {
              const eventSev = getSeverityColor(event.severity);
              return (
                <div key={idx} style={{ background: "var(--surface)", border: `1px solid ${eventSev.bg}40`, borderRadius: 8, padding: 10, display: "flex", gap: 8 }}>
                  <div style={{ width: 32, height: 32, background: eventSev.bg, borderRadius: 4, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 14, flexShrink: 0 }}>
                    📌
                  </div>
                  <div style={{ flex: 1, fontSize: 11 }}>
                    <div style={{ fontWeight: 600, color: "var(--text)", marginBottom: 2 }}>{event.type || event.event_type || "Security Event"}</div>
                    <div style={{ color: "var(--text-secondary)", fontSize: 10 }}>{event.description || event.message || "Suspicious activity detected"}</div>
                    <div style={{ color: eventSev.bg, fontSize: 10, marginTop: 2, fontWeight: 600 }}>Severity: {event.severity}</div>
                  </div>
                </div>
              );
            })}
            {result.details.siem_events.length > 8 && (
              <div style={{ background: "rgba(255,255,255,0.05)", borderRadius: 8, padding: 10, textAlign: "center", color: "var(--text-secondary)", fontSize: 11 }}>
                ... and {result.details.siem_events.length - 8} more events
              </div>
            )}
          </div>
        </div>
      )}

      {/* Recommendations */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 16, fontWeight: 800, marginBottom: 12, color: "var(--text)" }}>💡 What Should You Do?</div>
        <div style={{ display: "grid", gap: 10 }}>
          {result.summary.vulnerability_summary?.critical > 0 && (
            <div style={{ background: "var(--surface)", border: "1px solid rgba(255,0,0,0.3)", borderRadius: 8, padding: 14 }}>
              <div style={{ fontWeight: 800, marginBottom: 6, color: "#ff2d55" }}>Priority 1: Fix Critical Issues (Today)</div>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>Stop and fix critical vulnerabilities immediately. These could allow attackers to compromise your system. Consider taking the affected service offline until fixed. Patch all known vulnerabilities from your software vendors.</div>
            </div>
          )}
          {result.summary.vulnerability_summary?.high > 0 && (
            <div style={{ background: "var(--surface)", border: "1px solid rgba(255,153,0,0.3)", borderRadius: 8, padding: 14 }}>
              <div style={{ fontWeight: 800, marginBottom: 6, color: "#ff9500" }}>Priority 2: Address High-Risk Issues (This Week)</div>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>Plan to fix these within 3-5 days. Apply security patches and updates from your software vendors as soon as they're available. Test patches in a non-production environment first.</div>
            </div>
          )}
          {result.summary.defence?.fail > 0 && (
            <div style={{ background: "var(--surface)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, padding: 14 }}>
              <div style={{ fontWeight: 800, marginBottom: 6, color: "#3B82F6" }}>Priority 3: Improve Configuration ({result.summary.defence.fail} Failures)</div>
              <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>Review and fix failed security configuration checks. Enable security headers, configure firewalls properly, and enable logging and monitoring.</div>
            </div>
          )}
          <div style={{ background: "var(--surface)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, padding: 14 }}>
            <div style={{ fontWeight: 800, marginBottom: 6, color: "#45dfa4" }}>Ongoing Security Practices</div>
            <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>
              • Keep all software, systems, and plugins updated<br/>
              • Use strong, unique passwords with 2FA enabled<br/>
              • Regularly monitor security logs and alerts<br/>
              • Back up your data regularly and test restoration<br/>
              • Run security scans monthly and after changes<br/>
              • Train staff on phishing and social engineering
            </div>
          </div>
        </div>
      </div>

      {/* Report Info */}
      <div style={{ borderTop: "1px solid var(--ghost)", paddingTop: 16, color: "var(--text-secondary)", fontSize: 10 }}>
        <div style={{ marginBottom: 6 }}><strong>Report Generated:</strong> {new Date().toLocaleString()}</div>
        <div style={{ marginBottom: 6 }}><strong>Target Asset:</strong> {target}</div>
        <div style={{ marginBottom: 6 }}><strong>Analyst:</strong> {author}</div>
        <div style={{ marginBottom: 6 }}><strong>Organization:</strong> {orgName}</div>
        <div>This report is confidential and should only be shared with authorized personnel.</div>
      </div>
    </div>
  ) : (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", height: 400, color: "var(--text-secondary)" }}>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 48, marginBottom: 12 }}>📋</div>
        <div style={{ fontSize: 14 }}>Generate a report to see the detailed security analysis</div>
      </div>
    </div>
  );

  return (
    <>
      <PageTitle title="Security Report" subtitle="Detailed findings in simple language for everyone to understand." />

      <div className="grid" style={{ gridTemplateColumns: "minmax(320px, 400px) minmax(0, 1fr)", gap: 16, alignItems: "start" }}>
        <Card title="REPORT SETTINGS" subtitle="Customize your report">
          <div style={{ display: "grid", gap: 12 }}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.14em", color: "var(--text-muted)", marginBottom: 8 }}>ORGANIZATION NAME</div>
              <input value={orgName} onChange={(e) => setOrgName(e.target.value)} style={{ width: "100%", background: "var(--surface)", border: "1px solid var(--ghost)", color: "var(--text)", padding: 12, borderRadius: 6 }} />
            </div>
            <div>
              <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.14em", color: "var(--text-muted)", marginBottom: 8 }}>TARGET / ASSET</div>
              <input value={target} onChange={(e) => setTarget(e.target.value)} style={{ width: "100%", background: "var(--surface)", border: "1px solid var(--ghost)", color: "var(--text)", padding: 12, borderRadius: 6 }} />
            </div>
            <div>
              <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: "0.14em", color: "var(--text-muted)", marginBottom: 8 }}>ANALYST NAME</div>
              <input value={author} onChange={(e) => setAuthor(e.target.value)} style={{ width: "100%", background: "var(--surface)", border: "1px solid var(--ghost)", color: "var(--text)", padding: 12, borderRadius: 6 }} />
            </div>
            
            {error && (
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <p style={{ color: "#ffb4ab", fontSize: 12, margin: 0 }}>❌ {error}</p>
                <button 
                  onClick={() => { setError(""); window.location.reload(); }}
                  style={{ padding: "4px 12px", borderRadius: 6, border: "1px solid var(--surface-high)", background: "var(--surface)", color: "var(--primary)", cursor: "pointer", fontSize: 12, whiteSpace: "nowrap" }}
                >
                  Retry
                </button>
              </div>
            )}
            {generating && <p style={{ color: "#b4c5ff", fontSize: 12 }}>⏳ Generating report...</p>}
            
            <Button onClick={() => generate(false)} style={{ marginTop: 8 }}>
              {generating ? "Generating..." : "📊 Generate Report"}
            </Button>
            
            {result && (
              <>
                <div style={{ borderTop: "1px solid rgba(67,70,85,0.15)", paddingTop: 12, marginTop: 12 }}>
                  <div style={{ fontSize: 11, color: "var(--text-secondary)", fontWeight: 800, letterSpacing: "0.14em", marginBottom: 8 }}>DOWNLOAD OPTIONS</div>
                  <Button variant="secondary" onClick={downloadPDF} style={{ width: "100%", marginBottom: 8 }} disabled={generating}>
                    {generating ? "Generating PDF..." : "📥 Download as PDF"}
                  </Button>
                  <Button variant="secondary" onClick={viewFull} style={{ width: "100%", marginBottom: 8 }}>
                    🖨️ Print Report
                  </Button>
                  <Button variant="secondary" onClick={emailReport} style={{ width: "100%" }}>
                    📧 Email Report
                  </Button>
                </div>
                {result.pdf_path && (
                  <div style={{ background: "var(--surface)", border: "1px solid rgba(52,199,89,0.3)", borderRadius: 6, padding: 10, marginTop: 12 }}>
                    <div style={{ fontSize: 11, color: "#34c759", fontWeight: 800, marginBottom: 4 }}>✓ PDF Generated</div>
                    <div style={{ fontSize: 10, color: "var(--text-secondary)", wordBreak: "break-all" }}>{result.pdf_path}</div>
                  </div>
                )}
              </>
            )}
          </div>
        </Card>

        <div style={{ background: "var(--surface)", borderRadius: 8, border: "1px solid var(--ghost)", padding: 28 }}>
          {reportContent}
        </div>
      </div>
    </>
  );
}
